--------------------------------------------------------
--  ÆÄÀÏÀÌ »ý¼ºµÊ - ±Ý¿äÀÏ-5¿ù-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SAMPLE_BOARDS
--------------------------------------------------------

  CREATE TABLE "HR"."SAMPLE_BOARDS" 
   (	"BOARD_NO" NUMBER(7,0), 
	"BOARD_TITLE" VARCHAR2(500 BYTE), 
	"BOARD_WRITER" VARCHAR2(20 BYTE), 
	"BOARD_CONTENT" VARCHAR2(4000 BYTE), 
	"BOARD_HIT" NUMBER(7,0) DEFAULT 0, 
	"BOARD_REPLY_CNT" NUMBER(5,0) DEFAULT 0, 
	"BOARD_DEL_YN" CHAR(1 BYTE) DEFAULT 'N', 
	"BOARD_CREATE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAMPLE_USERS
--------------------------------------------------------

  CREATE TABLE "HR"."SAMPLE_USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"USER_PASSWORD" VARCHAR2(100 BYTE), 
	"USER_EMAIL" VARCHAR2(256 BYTE), 
	"USER_DISABLED" CHAR(1 BYTE) DEFAULT 'N', 
	"USER_CREATE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAMPLE_REPLYS
--------------------------------------------------------

  CREATE TABLE "HR"."SAMPLE_REPLYS" 
   (	"REPLY_NO" NUMBER(7,0), 
	"REPLY_WRITER" VARCHAR2(20 BYTE), 
	"REPLY_CONTENT" VARCHAR2(2000 BYTE), 
	"REPLY_DEL_YN" CHAR(1 BYTE) DEFAULT 'N', 
	"REPLY_CREATE_DATE" DATE DEFAULT sysdate, 
	"BOARD_NO" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.SAMPLE_BOARDS
SET DEFINE OFF;
Insert into HR.SAMPLE_BOARDS (BOARD_NO,BOARD_TITLE,BOARD_WRITER,BOARD_CONTENT,BOARD_HIT,BOARD_REPLY_CNT,BOARD_DEL_YN,BOARD_CREATE_DATE) values (12,'test','dahun429','test content',4,2,'N',to_date('20/05/29 11:41:47','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_BOARDS (BOARD_NO,BOARD_TITLE,BOARD_WRITER,BOARD_CONTENT,BOARD_HIT,BOARD_REPLY_CNT,BOARD_DEL_YN,BOARD_CREATE_DATE) values (13,'test','dahun429','test content',0,0,'Y',to_date('20/05/29 11:51:03','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_BOARDS (BOARD_NO,BOARD_TITLE,BOARD_WRITER,BOARD_CONTENT,BOARD_HIT,BOARD_REPLY_CNT,BOARD_DEL_YN,BOARD_CREATE_DATE) values (14,'¤·¤·¤·¤·¤·','dahun429','¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·¤·',2,0,'N',to_date('20/05/29 17:51:06','RR/MM/DD HH24:MI:SS'));
REM INSERTING into HR.SAMPLE_USERS
SET DEFINE OFF;
Insert into HR.SAMPLE_USERS (USER_ID,USER_NAME,USER_PASSWORD,USER_EMAIL,USER_DISABLED,USER_CREATE_DATE) values ('dahun429','Á¤´ÙÈÆ','1234','dd@nn','N',to_date('20/05/29 11:39:53','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_USERS (USER_ID,USER_NAME,USER_PASSWORD,USER_EMAIL,USER_DISABLED,USER_CREATE_DATE) values ('dahun427','?????¢´???','1234','rubcustomer@gmail.com','N',to_date('20/05/29 17:21:35','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_USERS (USER_ID,USER_NAME,USER_PASSWORD,USER_EMAIL,USER_DISABLED,USER_CREATE_DATE) values ('dahun425','Á¤´ÙÈÆ','1234','rubcustomer@gmail.com','N',to_date('20/05/29 17:37:21','RR/MM/DD HH24:MI:SS'));
REM INSERTING into HR.SAMPLE_REPLYS
SET DEFINE OFF;
Insert into HR.SAMPLE_REPLYS (REPLY_NO,REPLY_WRITER,REPLY_CONTENT,REPLY_DEL_YN,REPLY_CREATE_DATE,BOARD_NO) values (9,'dahun429','asdfsdf','N',to_date('20/05/29 17:59:41','RR/MM/DD HH24:MI:SS'),14);
Insert into HR.SAMPLE_REPLYS (REPLY_NO,REPLY_WRITER,REPLY_CONTENT,REPLY_DEL_YN,REPLY_CREATE_DATE,BOARD_NO) values (7,'dahun429','test content','N',to_date('20/05/29 12:38:32','RR/MM/DD HH24:MI:SS'),12);
Insert into HR.SAMPLE_REPLYS (REPLY_NO,REPLY_WRITER,REPLY_CONTENT,REPLY_DEL_YN,REPLY_CREATE_DATE,BOARD_NO) values (8,'dahun429','ggg','N',to_date('20/05/29 12:38:32','RR/MM/DD HH24:MI:SS'),12);
Insert into HR.SAMPLE_REPLYS (REPLY_NO,REPLY_WRITER,REPLY_CONTENT,REPLY_DEL_YN,REPLY_CREATE_DATE,BOARD_NO) values (10,'dahun429','dfgdfgfghfghg','N',to_date('20/05/29 17:59:44','RR/MM/DD HH24:MI:SS'),14);
--------------------------------------------------------
--  DDL for Index SAMPLE_BOARD_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SAMPLE_BOARD_NO_PK" ON "HR"."SAMPLE_BOARDS" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SAMPLE_USER_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SAMPLE_USER_ID_PK" ON "HR"."SAMPLE_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SAMPLE_REPLY_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SAMPLE_REPLY_NO" ON "HR"."SAMPLE_REPLYS" ("REPLY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SAMPLE_BOARDS
--------------------------------------------------------

  ALTER TABLE "HR"."SAMPLE_BOARDS" ADD CONSTRAINT "SAMPLE_BOARD_NO_PK" PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SAMPLE_BOARDS" MODIFY ("BOARD_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HR"."SAMPLE_BOARDS" MODIFY ("BOARD_WRITER" NOT NULL ENABLE);
  ALTER TABLE "HR"."SAMPLE_BOARDS" MODIFY ("BOARD_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SAMPLE_USERS
--------------------------------------------------------

  ALTER TABLE "HR"."SAMPLE_USERS" ADD CONSTRAINT "SAMPLE_USER_ID_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SAMPLE_USERS" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HR"."SAMPLE_USERS" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HR"."SAMPLE_USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SAMPLE_REPLYS
--------------------------------------------------------

  ALTER TABLE "HR"."SAMPLE_REPLYS" ADD CONSTRAINT "SAMPLE_REPLY_NO" PRIMARY KEY ("REPLY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SAMPLE_REPLYS" MODIFY ("REPLY_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HR"."SAMPLE_REPLYS" MODIFY ("REPLY_WRITER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SAMPLE_BOARDS
--------------------------------------------------------

  ALTER TABLE "HR"."SAMPLE_BOARDS" ADD CONSTRAINT "SAMLE_BOARD_WRITER_FK" FOREIGN KEY ("BOARD_WRITER")
	  REFERENCES "HR"."SAMPLE_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SAMPLE_REPLYS
--------------------------------------------------------

  ALTER TABLE "HR"."SAMPLE_REPLYS" ADD CONSTRAINT "SAMPLE_BOARD_NO_FK" FOREIGN KEY ("BOARD_NO")
	  REFERENCES "HR"."SAMPLE_BOARDS" ("BOARD_NO") ENABLE;
  ALTER TABLE "HR"."SAMPLE_REPLYS" ADD CONSTRAINT "SAMPLE_REPLY_WRITER_FK" FOREIGN KEY ("REPLY_WRITER")
	  REFERENCES "HR"."SAMPLE_USERS" ("USER_ID") ENABLE;
